name: GitOps Update

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: Docker image tag

permissions:
  contents: write

jobs:
  update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update image tag
        run: |
          sed -i 's/newTag:.*/newTag: "${{ inputs.image_tag }}"/' \
            environments/dev/demo-app/kustomization.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add environments/dev/demo-app/kustomization.yaml
          git commit -m "dev: update image tag to ${{ inputs.image_tag }}"
          git push origin gitops
